services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: go-app:latest
    container_name: go-app
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: unless-stopped
